package com.didispace.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.didispace.entity.Record;
import com.didispace.entity.RecordKey;
import com.didispace.viewEntity.VAttendanceStu;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int deleteByPrimaryKey(RecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    Record selectByPrimaryKey(RecordKey key);

    /**
     * 根据课次和课程编号查找签到列表
     * 返回值为：学生编号，学生名字，班级，签到情况
     * @param record
     * @return
     */
     List<VAttendanceStu> selectAtdanceStuByTimeIdByCId(
     		@Param("timeSlotId")Integer timeSlotId,
     		@Param("courseId")Integer courseId
     		);
    
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int updateByPrimaryKey(Record record);
}