package com.didispace.mapper;

import java.util.List;

import com.didispace.entity.Student;
import com.didispace.viewEntity.VStuAndClass;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Apr 25 15:08:32 CST 2019
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Apr 25 15:08:32 CST 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Apr 25 15:08:32 CST 2019
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Apr 25 15:08:32 CST 2019
     */
    Student selectByPrimaryKey(Integer sId);

    /**
     * 根据学生名字查找
     * @param sname
     * @param type
     * @return
     */
    Student selectBySname(String sname);

    /**
     * 根据课程编号查找学生名单
     * @param record
     * @return
     */
    List<VStuAndClass> selectByCId(Integer courseId);
    
    
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Apr 25 15:08:32 CST 2019
     */
    int updateByPrimaryKey(Student record);
}