package com.didispace.mapper;

import com.didispace.entity.TakesKey;

public interface TakesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int deleteByPrimaryKey(TakesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int insert(TakesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    int insertSelective(TakesKey record);
}