package com.didispace.entity;

public class PersonInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.user_id
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.type
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.user_id
     *
     * @return the value of person_info.user_id
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.user_id
     *
     * @param userId the value for person_info.user_id
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.type
     *
     * @return the value of person_info.type
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.type
     *
     * @param type the value for person_info.type
     *
     * @mbg.generated Thu Apr 25 16:10:04 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}