package com.didispace.entity;

public class RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer timeSlotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.s_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer sId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time_slot_id
     *
     * @return the value of record.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getTimeSlotId() {
        return timeSlotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time_slot_id
     *
     * @param timeSlotId the value for record.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setTimeSlotId(Integer timeSlotId) {
        this.timeSlotId = timeSlotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.s_id
     *
     * @return the value of record.s_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.s_id
     *
     * @param sId the value for record.s_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}