package com.didispace.entity;

public class SectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.course_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sec_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer secId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.course_id
     *
     * @return the value of section.course_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.course_id
     *
     * @param courseId the value for section.course_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sec_id
     *
     * @return the value of section.sec_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sec_id
     *
     * @param secId the value for section.sec_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setSecId(Integer secId) {
        this.secId = secId;
    }
}