package com.didispace.entity;

public class Section extends SectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.secOfCourse
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer secofcourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Integer timeSlotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.status
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.secOfCourse
     *
     * @return the value of section.secOfCourse
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getSecofcourse() {
        return secofcourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.secOfCourse
     *
     * @param secofcourse the value for section.secOfCourse
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setSecofcourse(Integer secofcourse) {
        this.secofcourse = secofcourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.time_slot_id
     *
     * @return the value of section.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Integer getTimeSlotId() {
        return timeSlotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.time_slot_id
     *
     * @param timeSlotId the value for section.time_slot_id
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setTimeSlotId(Integer timeSlotId) {
        this.timeSlotId = timeSlotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.status
     *
     * @return the value of section.status
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.status
     *
     * @param status the value for section.status
     *
     * @mbg.generated Thu Apr 25 16:04:33 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}